remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: tuputepadre

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  members:
    output: true

# minima:
#   skin: dark

author:
  name: oscar novillo
  
