theme: minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: hola ASIR2

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  members:
    output: true

plugins:
  - jekyll-paginate

# número de posts por página
paginate: 2
paginate_path: "/blog/page:num/"

minima:
  skin: dark

author:
  name: oscar novillo
  
